version: '2'
services:
  monocache:
      image: steamcache/monolithic:latest
    ports:
        - ${CACHE_IP}:80:80
    environment:
      CACHE_MONOLITHIC: true
      CACHE_DISK_SIZE: ${CACHE_DISK_SIZE}m
      CACHE_MEM_SIZE: ${CACHE_MEM_SIZE}m
      CACHE_MAX_AGE: ${CACHE_MAX_AGE}d
    volumes:
      - ${CACHE_ROOT}/cache:/data/cache
      - ${CACHE_ROOT}/logs:/data/logs
      - ${CACHE_ROOT}/cachedomains:/data/cachedomains
  sniproxy:
    image: steamcache/sniproxy:latest
    ports:
        - 443:443/tcp
  dns:
    image: steamcache/steamcache-dns:latest
    ports:
      - 53:53/udp
    environment:
      USE_GENERIC_CACHE: false
      UPSTREAM_DNS: ${UPSTREAM_DNS}
      APPLECACHE_IP: ${CACHE_IP}
      DISABLE_APPLE: ${DISABLE_APPLE}
      ARENANETCACHE_IP: ${CACHE_IP}
      DISABLE_ARENANET: ${DISABLE_ARENANET}
      BLIZZARDCACHE_IP: ${CACHE_IP}
      DISABLE_BLIZZARD: ${DISABLE_BLIZZARD}
      DAYBREAKCACHE_IP: ${CACHE_IP}
      DISABLE_DAYBREAK: ${DISABLE_DAYBREAK}
      FRONTIERCACHE_IP: ${CACHE_IP}
      DISABLE_FRONTIER: ${DISABLE_FRONTIER}
      HIREZCACHE_IP: ${CACHE_IP}
      DISABLE_HIREZ: ${DISABLE_HIREZ}
      MINECRAFTCACHE_IP: ${CACHE_IP}
      DISABLE_MINECRAFT: ${DISABLE_MINECRAFT}
      NEXUSMODSCACHE_IP: ${CACHE_IP}
      DISABLE_NEXUSMODS: ${DISABLE_NEXUSMODS}
      NINTENDOCACHE_IP: ${CACHE_IP}
      DISABLE_NINTENDO: ${DISABLE_NINTENDO}
      ORIGINCACHE_IP: ${CACHE_IP}
      DISABLE_ORIGIN: ${DISABLE_ORIGIN}
      RENEGADEXCACHE_IP: ${CACHE_IP}
      DISABLE_RENEGADEX: ${DISABLE_RENEGADEX}
      RIOTCACHE_IP: ${CACHE_IP}
      DISABLE_RIOT: ${DISABLE_RIOT}
      ROCKSTARCACHE_IP: ${CACHE_IP}
      DISABLE_ROCKSTAR: ${DISABLE_ROCKSTAR}
      SONYCACHE_IP: ${CACHE_IP}
      DISABLE_SONY: ${DISABLE_SONY}
      STEAMCACHE_IP: ${CACHE_IP}
      DISABLE_STEAM: ${DISABLE_STEAM}
      UPLAYCACHE_IP: ${CACHE_IP}
      DISABLE_UPLAY: ${DISABLE_UPLAY}
      TWITCHCACHE_IP: ${CACHE_IP}
      DISABLE_TWITCH: ${DISABLE_TWITCH}
      WARGAMINGCACHE_IP: ${CACHE_IP}
      DISABLE_WARGAMING: ${DISABLE_WARGAMING}
      WSUSCACHE_IP: ${CACHE_IP}
      DISABLE_WSUS: ${DISABLE_WSUS}
      XBOXLIVECACHE_IP: ${CACHE_IP}
      DISABLE_XBOXLIVE: ${DISABLE_XBOXLIVE}
